nodeLinker: node-modules

npmPublishRegistry: "http://8.141.152.4:4873/"

npmRegistries:
  "http://8.141.152.4:4873/":
    npmAuthToken: LTW5QZHrSedwHWoOTpqrDg==

npmRegistryServer: "https://registry.npmmirror.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

unsafeHttpWhitelist:
  - 8.141.152.4

yarnPath: .yarn/releases/yarn-3.2.4.cjs
